name: Docker CI/CD v2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
          python-version: '3.10.14'
     
     - name: Install dependencies
       run: |
          python -m pip install --upgrade pip
          pip install pylint
     
     - name: Analysing the code with pylint
       run: |
        pylint --disable=E0401 --exit-zero main.py src/modules/*.py
        
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webscraper:latest
     
      - name: Set Docker tags in environment
        run: echo "DOCKER_TAGS=${{ secrets.DOCKER_USERNAME }}/webscraper:latest" >> $GITHUB_ENV
     
      - name: Run Docker container
        run: |
          echo SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} > .env
          echo SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }} >> .env
          echo RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }} >> .env
          echo FIRST_KEYWORD=${{ secrets.FIRST_KEYWORD }} >> .env
          echo SECOND_KEYWORD=${{ secrets.SECOND_KEYWORD }} >> .env
          echo THIRD_KEYWORD=${{ secrets.THIRD_KEYWORD }} >> .env
          docker run -it --env-file=.env $DOCKER_TAGS python main.py
        env:
            SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
            SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
            RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
            FIRST_KEYWORD: ${{ secrets.FIRST_KEYWORD }}
            SECOND_KEYWORD: ${{ secrets.SECOND_KEYWORD }}
            THIRD_KEYWORD: ${{ secrets.THIRD_KEYWORD }}
